facebook: https://www.facebook.com/blackmovementlawproject
# Without the @ sign
twitter: "Black_MLP"
# When you generate an embedded mailchimp form, provide thus url. Append -json to subscribe/post, as you see below.
mailchimp_form_url: "//bmlp.us11.list-manage.com/subscribe/post-json?u=4caff5c5b26c1b3239a668641&amp;id=16efa33510"
# Note: changing contact email requires an email confirmation.
#  If you change it, submit the form and then confirm from your inbox.
contactemail: info@bmlp.org
# Contact form submissions are cc'd to this address
#contactemailalt: info@bmlp.org

contactphone: (347) 504-9001
# Postal address line1 & 2
address_header: "Make Tax-Deductible Donations to:"
address:
  - "BMLP/AfGJ"
  - "225 E. 26th St., Suite 1"
  - "Tucson, AZ 85713"
